/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AddressResponseDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-06T14:15:06.398175800+03:00[Europe/Helsinki]")
public class AddressResponseDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("adr_id")
  private Integer adrId = null;

  @SerializedName("koodaadress")
  private Integer koodaadress = null;

  @SerializedName("taisaadress")
  private Integer taisaadress = null;

  @SerializedName("lahiaadress")
  private Integer lahiaadress = null;

  @SerializedName("tase1_id")
  private Integer tase1Id = null;

  @SerializedName("tase1_kood")
  private Integer tase1Kood = null;

  @SerializedName("tase1_nimetus")
  private Integer tase1Nimetus = null;

  @SerializedName("tase2_id")
  private Integer tase2Id = null;

  @SerializedName("tase2_kood")
  private Integer tase2Kood = null;

  @SerializedName("tase2_nimetus")
  private Integer tase2Nimetus = null;

  @SerializedName("tase3_id")
  private Integer tase3Id = null;

  @SerializedName("tase3_nimetus")
  private Integer tase3Nimetus = null;

  @SerializedName("tase4_id")
  private Integer tase4Id = null;

  @SerializedName("tase4_nimetus")
  private Integer tase4Nimetus = null;

  @SerializedName("tase5_id")
  private Integer tase5Id = null;

  @SerializedName("tase5_nimetus")
  private Integer tase5Nimetus = null;

  @SerializedName("tase6_id")
  private Integer tase6Id = null;

  @SerializedName("tase6_nimetus")
  private Integer tase6Nimetus = null;

  @SerializedName("tase7_id")
  private Integer tase7Id = null;

  @SerializedName("tase7_nimetus")
  private Integer tase7Nimetus = null;

  @SerializedName("tase8_id")
  private Integer tase8Id = null;

  @SerializedName("tase8_nimetus")
  private Integer tase8Nimetus = null;

  @SerializedName("koord_x")
  private Integer koordX = null;

  @SerializedName("koord_y")
  private Integer koordY = null;

  public AddressResponseDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AddressResponseDTO adrId(Integer adrId) {
    this.adrId = adrId;
    return this;
  }

   /**
   * Get adrId
   * @return adrId
  **/
  @Schema(description = "")
  public Integer getAdrId() {
    return adrId;
  }

  public void setAdrId(Integer adrId) {
    this.adrId = adrId;
  }

  public AddressResponseDTO koodaadress(Integer koodaadress) {
    this.koodaadress = koodaadress;
    return this;
  }

   /**
   * Get koodaadress
   * @return koodaadress
  **/
  @Schema(description = "")
  public Integer getKoodaadress() {
    return koodaadress;
  }

  public void setKoodaadress(Integer koodaadress) {
    this.koodaadress = koodaadress;
  }

  public AddressResponseDTO taisaadress(Integer taisaadress) {
    this.taisaadress = taisaadress;
    return this;
  }

   /**
   * Get taisaadress
   * @return taisaadress
  **/
  @Schema(description = "")
  public Integer getTaisaadress() {
    return taisaadress;
  }

  public void setTaisaadress(Integer taisaadress) {
    this.taisaadress = taisaadress;
  }

  public AddressResponseDTO lahiaadress(Integer lahiaadress) {
    this.lahiaadress = lahiaadress;
    return this;
  }

   /**
   * Get lahiaadress
   * @return lahiaadress
  **/
  @Schema(description = "")
  public Integer getLahiaadress() {
    return lahiaadress;
  }

  public void setLahiaadress(Integer lahiaadress) {
    this.lahiaadress = lahiaadress;
  }

  public AddressResponseDTO tase1Id(Integer tase1Id) {
    this.tase1Id = tase1Id;
    return this;
  }

   /**
   * Get tase1Id
   * @return tase1Id
  **/
  @Schema(description = "")
  public Integer getTase1Id() {
    return tase1Id;
  }

  public void setTase1Id(Integer tase1Id) {
    this.tase1Id = tase1Id;
  }

  public AddressResponseDTO tase1Kood(Integer tase1Kood) {
    this.tase1Kood = tase1Kood;
    return this;
  }

   /**
   * Get tase1Kood
   * @return tase1Kood
  **/
  @Schema(description = "")
  public Integer getTase1Kood() {
    return tase1Kood;
  }

  public void setTase1Kood(Integer tase1Kood) {
    this.tase1Kood = tase1Kood;
  }

  public AddressResponseDTO tase1Nimetus(Integer tase1Nimetus) {
    this.tase1Nimetus = tase1Nimetus;
    return this;
  }

   /**
   * Get tase1Nimetus
   * @return tase1Nimetus
  **/
  @Schema(description = "")
  public Integer getTase1Nimetus() {
    return tase1Nimetus;
  }

  public void setTase1Nimetus(Integer tase1Nimetus) {
    this.tase1Nimetus = tase1Nimetus;
  }

  public AddressResponseDTO tase2Id(Integer tase2Id) {
    this.tase2Id = tase2Id;
    return this;
  }

   /**
   * Get tase2Id
   * @return tase2Id
  **/
  @Schema(description = "")
  public Integer getTase2Id() {
    return tase2Id;
  }

  public void setTase2Id(Integer tase2Id) {
    this.tase2Id = tase2Id;
  }

  public AddressResponseDTO tase2Kood(Integer tase2Kood) {
    this.tase2Kood = tase2Kood;
    return this;
  }

   /**
   * Get tase2Kood
   * @return tase2Kood
  **/
  @Schema(description = "")
  public Integer getTase2Kood() {
    return tase2Kood;
  }

  public void setTase2Kood(Integer tase2Kood) {
    this.tase2Kood = tase2Kood;
  }

  public AddressResponseDTO tase2Nimetus(Integer tase2Nimetus) {
    this.tase2Nimetus = tase2Nimetus;
    return this;
  }

   /**
   * Get tase2Nimetus
   * @return tase2Nimetus
  **/
  @Schema(description = "")
  public Integer getTase2Nimetus() {
    return tase2Nimetus;
  }

  public void setTase2Nimetus(Integer tase2Nimetus) {
    this.tase2Nimetus = tase2Nimetus;
  }

  public AddressResponseDTO tase3Id(Integer tase3Id) {
    this.tase3Id = tase3Id;
    return this;
  }

   /**
   * Get tase3Id
   * @return tase3Id
  **/
  @Schema(description = "")
  public Integer getTase3Id() {
    return tase3Id;
  }

  public void setTase3Id(Integer tase3Id) {
    this.tase3Id = tase3Id;
  }

  public AddressResponseDTO tase3Nimetus(Integer tase3Nimetus) {
    this.tase3Nimetus = tase3Nimetus;
    return this;
  }

   /**
   * Get tase3Nimetus
   * @return tase3Nimetus
  **/
  @Schema(description = "")
  public Integer getTase3Nimetus() {
    return tase3Nimetus;
  }

  public void setTase3Nimetus(Integer tase3Nimetus) {
    this.tase3Nimetus = tase3Nimetus;
  }

  public AddressResponseDTO tase4Id(Integer tase4Id) {
    this.tase4Id = tase4Id;
    return this;
  }

   /**
   * Get tase4Id
   * @return tase4Id
  **/
  @Schema(description = "")
  public Integer getTase4Id() {
    return tase4Id;
  }

  public void setTase4Id(Integer tase4Id) {
    this.tase4Id = tase4Id;
  }

  public AddressResponseDTO tase4Nimetus(Integer tase4Nimetus) {
    this.tase4Nimetus = tase4Nimetus;
    return this;
  }

   /**
   * Get tase4Nimetus
   * @return tase4Nimetus
  **/
  @Schema(description = "")
  public Integer getTase4Nimetus() {
    return tase4Nimetus;
  }

  public void setTase4Nimetus(Integer tase4Nimetus) {
    this.tase4Nimetus = tase4Nimetus;
  }

  public AddressResponseDTO tase5Id(Integer tase5Id) {
    this.tase5Id = tase5Id;
    return this;
  }

   /**
   * Get tase5Id
   * @return tase5Id
  **/
  @Schema(description = "")
  public Integer getTase5Id() {
    return tase5Id;
  }

  public void setTase5Id(Integer tase5Id) {
    this.tase5Id = tase5Id;
  }

  public AddressResponseDTO tase5Nimetus(Integer tase5Nimetus) {
    this.tase5Nimetus = tase5Nimetus;
    return this;
  }

   /**
   * Get tase5Nimetus
   * @return tase5Nimetus
  **/
  @Schema(description = "")
  public Integer getTase5Nimetus() {
    return tase5Nimetus;
  }

  public void setTase5Nimetus(Integer tase5Nimetus) {
    this.tase5Nimetus = tase5Nimetus;
  }

  public AddressResponseDTO tase6Id(Integer tase6Id) {
    this.tase6Id = tase6Id;
    return this;
  }

   /**
   * Get tase6Id
   * @return tase6Id
  **/
  @Schema(description = "")
  public Integer getTase6Id() {
    return tase6Id;
  }

  public void setTase6Id(Integer tase6Id) {
    this.tase6Id = tase6Id;
  }

  public AddressResponseDTO tase6Nimetus(Integer tase6Nimetus) {
    this.tase6Nimetus = tase6Nimetus;
    return this;
  }

   /**
   * Get tase6Nimetus
   * @return tase6Nimetus
  **/
  @Schema(description = "")
  public Integer getTase6Nimetus() {
    return tase6Nimetus;
  }

  public void setTase6Nimetus(Integer tase6Nimetus) {
    this.tase6Nimetus = tase6Nimetus;
  }

  public AddressResponseDTO tase7Id(Integer tase7Id) {
    this.tase7Id = tase7Id;
    return this;
  }

   /**
   * Get tase7Id
   * @return tase7Id
  **/
  @Schema(description = "")
  public Integer getTase7Id() {
    return tase7Id;
  }

  public void setTase7Id(Integer tase7Id) {
    this.tase7Id = tase7Id;
  }

  public AddressResponseDTO tase7Nimetus(Integer tase7Nimetus) {
    this.tase7Nimetus = tase7Nimetus;
    return this;
  }

   /**
   * Get tase7Nimetus
   * @return tase7Nimetus
  **/
  @Schema(description = "")
  public Integer getTase7Nimetus() {
    return tase7Nimetus;
  }

  public void setTase7Nimetus(Integer tase7Nimetus) {
    this.tase7Nimetus = tase7Nimetus;
  }

  public AddressResponseDTO tase8Id(Integer tase8Id) {
    this.tase8Id = tase8Id;
    return this;
  }

   /**
   * Get tase8Id
   * @return tase8Id
  **/
  @Schema(description = "")
  public Integer getTase8Id() {
    return tase8Id;
  }

  public void setTase8Id(Integer tase8Id) {
    this.tase8Id = tase8Id;
  }

  public AddressResponseDTO tase8Nimetus(Integer tase8Nimetus) {
    this.tase8Nimetus = tase8Nimetus;
    return this;
  }

   /**
   * Get tase8Nimetus
   * @return tase8Nimetus
  **/
  @Schema(description = "")
  public Integer getTase8Nimetus() {
    return tase8Nimetus;
  }

  public void setTase8Nimetus(Integer tase8Nimetus) {
    this.tase8Nimetus = tase8Nimetus;
  }

  public AddressResponseDTO koordX(Integer koordX) {
    this.koordX = koordX;
    return this;
  }

   /**
   * Get koordX
   * @return koordX
  **/
  @Schema(description = "")
  public Integer getKoordX() {
    return koordX;
  }

  public void setKoordX(Integer koordX) {
    this.koordX = koordX;
  }

  public AddressResponseDTO koordY(Integer koordY) {
    this.koordY = koordY;
    return this;
  }

   /**
   * Get koordY
   * @return koordY
  **/
  @Schema(description = "")
  public Integer getKoordY() {
    return koordY;
  }

  public void setKoordY(Integer koordY) {
    this.koordY = koordY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressResponseDTO addressResponseDTO = (AddressResponseDTO) o;
    return Objects.equals(this.id, addressResponseDTO.id) &&
        Objects.equals(this.adrId, addressResponseDTO.adrId) &&
        Objects.equals(this.koodaadress, addressResponseDTO.koodaadress) &&
        Objects.equals(this.taisaadress, addressResponseDTO.taisaadress) &&
        Objects.equals(this.lahiaadress, addressResponseDTO.lahiaadress) &&
        Objects.equals(this.tase1Id, addressResponseDTO.tase1Id) &&
        Objects.equals(this.tase1Kood, addressResponseDTO.tase1Kood) &&
        Objects.equals(this.tase1Nimetus, addressResponseDTO.tase1Nimetus) &&
        Objects.equals(this.tase2Id, addressResponseDTO.tase2Id) &&
        Objects.equals(this.tase2Kood, addressResponseDTO.tase2Kood) &&
        Objects.equals(this.tase2Nimetus, addressResponseDTO.tase2Nimetus) &&
        Objects.equals(this.tase3Id, addressResponseDTO.tase3Id) &&
        Objects.equals(this.tase3Nimetus, addressResponseDTO.tase3Nimetus) &&
        Objects.equals(this.tase4Id, addressResponseDTO.tase4Id) &&
        Objects.equals(this.tase4Nimetus, addressResponseDTO.tase4Nimetus) &&
        Objects.equals(this.tase5Id, addressResponseDTO.tase5Id) &&
        Objects.equals(this.tase5Nimetus, addressResponseDTO.tase5Nimetus) &&
        Objects.equals(this.tase6Id, addressResponseDTO.tase6Id) &&
        Objects.equals(this.tase6Nimetus, addressResponseDTO.tase6Nimetus) &&
        Objects.equals(this.tase7Id, addressResponseDTO.tase7Id) &&
        Objects.equals(this.tase7Nimetus, addressResponseDTO.tase7Nimetus) &&
        Objects.equals(this.tase8Id, addressResponseDTO.tase8Id) &&
        Objects.equals(this.tase8Nimetus, addressResponseDTO.tase8Nimetus) &&
        Objects.equals(this.koordX, addressResponseDTO.koordX) &&
        Objects.equals(this.koordY, addressResponseDTO.koordY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adrId, koodaadress, taisaadress, lahiaadress, tase1Id, tase1Kood, tase1Nimetus, tase2Id, tase2Kood, tase2Nimetus, tase3Id, tase3Nimetus, tase4Id, tase4Nimetus, tase5Id, tase5Nimetus, tase6Id, tase6Nimetus, tase7Id, tase7Nimetus, tase8Id, tase8Nimetus, koordX, koordY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressResponseDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adrId: ").append(toIndentedString(adrId)).append("\n");
    sb.append("    koodaadress: ").append(toIndentedString(koodaadress)).append("\n");
    sb.append("    taisaadress: ").append(toIndentedString(taisaadress)).append("\n");
    sb.append("    lahiaadress: ").append(toIndentedString(lahiaadress)).append("\n");
    sb.append("    tase1Id: ").append(toIndentedString(tase1Id)).append("\n");
    sb.append("    tase1Kood: ").append(toIndentedString(tase1Kood)).append("\n");
    sb.append("    tase1Nimetus: ").append(toIndentedString(tase1Nimetus)).append("\n");
    sb.append("    tase2Id: ").append(toIndentedString(tase2Id)).append("\n");
    sb.append("    tase2Kood: ").append(toIndentedString(tase2Kood)).append("\n");
    sb.append("    tase2Nimetus: ").append(toIndentedString(tase2Nimetus)).append("\n");
    sb.append("    tase3Id: ").append(toIndentedString(tase3Id)).append("\n");
    sb.append("    tase3Nimetus: ").append(toIndentedString(tase3Nimetus)).append("\n");
    sb.append("    tase4Id: ").append(toIndentedString(tase4Id)).append("\n");
    sb.append("    tase4Nimetus: ").append(toIndentedString(tase4Nimetus)).append("\n");
    sb.append("    tase5Id: ").append(toIndentedString(tase5Id)).append("\n");
    sb.append("    tase5Nimetus: ").append(toIndentedString(tase5Nimetus)).append("\n");
    sb.append("    tase6Id: ").append(toIndentedString(tase6Id)).append("\n");
    sb.append("    tase6Nimetus: ").append(toIndentedString(tase6Nimetus)).append("\n");
    sb.append("    tase7Id: ").append(toIndentedString(tase7Id)).append("\n");
    sb.append("    tase7Nimetus: ").append(toIndentedString(tase7Nimetus)).append("\n");
    sb.append("    tase8Id: ").append(toIndentedString(tase8Id)).append("\n");
    sb.append("    tase8Nimetus: ").append(toIndentedString(tase8Nimetus)).append("\n");
    sb.append("    koordX: ").append(toIndentedString(koordX)).append("\n");
    sb.append("    koordY: ").append(toIndentedString(koordY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
