/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ComponentDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * AddressRequestDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-06T14:15:06.398175800+03:00[Europe/Helsinki]")
public class AddressRequestDTO {
  @SerializedName("adrId")
  private Integer adrId = null;

  @SerializedName("pointX")
  private BigDecimal pointX = null;

  @SerializedName("pointY")
  private BigDecimal pointY = null;

  @SerializedName("adsAdrId")
  private Integer adsAdrId = null;

  @SerializedName("codeAddress")
  private String codeAddress = null;

  @SerializedName("closeAddress")
  private String closeAddress = null;

  @SerializedName("fullAddress")
  private String fullAddress = null;

  @SerializedName("component1")
  private ComponentDTO component1 = null;

  @SerializedName("component2")
  private ComponentDTO component2 = null;

  @SerializedName("component3")
  private ComponentDTO component3 = null;

  @SerializedName("component4")
  private ComponentDTO component4 = null;

  @SerializedName("component5")
  private ComponentDTO component5 = null;

  @SerializedName("component6")
  private ComponentDTO component6 = null;

  @SerializedName("component7")
  private ComponentDTO component7 = null;

  @SerializedName("component8")
  private ComponentDTO component8 = null;

  public AddressRequestDTO adrId(Integer adrId) {
    this.adrId = adrId;
    return this;
  }

   /**
   * Get adrId
   * @return adrId
  **/
  @Schema(description = "")
  public Integer getAdrId() {
    return adrId;
  }

  public void setAdrId(Integer adrId) {
    this.adrId = adrId;
  }

  public AddressRequestDTO pointX(BigDecimal pointX) {
    this.pointX = pointX;
    return this;
  }

   /**
   * Get pointX
   * @return pointX
  **/
  @Schema(description = "")
  public BigDecimal getPointX() {
    return pointX;
  }

  public void setPointX(BigDecimal pointX) {
    this.pointX = pointX;
  }

  public AddressRequestDTO pointY(BigDecimal pointY) {
    this.pointY = pointY;
    return this;
  }

   /**
   * Get pointY
   * @return pointY
  **/
  @Schema(description = "")
  public BigDecimal getPointY() {
    return pointY;
  }

  public void setPointY(BigDecimal pointY) {
    this.pointY = pointY;
  }

  public AddressRequestDTO adsAdrId(Integer adsAdrId) {
    this.adsAdrId = adsAdrId;
    return this;
  }

   /**
   * Get adsAdrId
   * @return adsAdrId
  **/
  @Schema(description = "")
  public Integer getAdsAdrId() {
    return adsAdrId;
  }

  public void setAdsAdrId(Integer adsAdrId) {
    this.adsAdrId = adsAdrId;
  }

  public AddressRequestDTO codeAddress(String codeAddress) {
    this.codeAddress = codeAddress;
    return this;
  }

   /**
   * Get codeAddress
   * @return codeAddress
  **/
  @Schema(description = "")
  public String getCodeAddress() {
    return codeAddress;
  }

  public void setCodeAddress(String codeAddress) {
    this.codeAddress = codeAddress;
  }

  public AddressRequestDTO closeAddress(String closeAddress) {
    this.closeAddress = closeAddress;
    return this;
  }

   /**
   * Get closeAddress
   * @return closeAddress
  **/
  @Schema(description = "")
  public String getCloseAddress() {
    return closeAddress;
  }

  public void setCloseAddress(String closeAddress) {
    this.closeAddress = closeAddress;
  }

  public AddressRequestDTO fullAddress(String fullAddress) {
    this.fullAddress = fullAddress;
    return this;
  }

   /**
   * Get fullAddress
   * @return fullAddress
  **/
  @Schema(description = "")
  public String getFullAddress() {
    return fullAddress;
  }

  public void setFullAddress(String fullAddress) {
    this.fullAddress = fullAddress;
  }

  public AddressRequestDTO component1(ComponentDTO component1) {
    this.component1 = component1;
    return this;
  }

   /**
   * Get component1
   * @return component1
  **/
  @Schema(description = "")
  public ComponentDTO getComponent1() {
    return component1;
  }

  public void setComponent1(ComponentDTO component1) {
    this.component1 = component1;
  }

  public AddressRequestDTO component2(ComponentDTO component2) {
    this.component2 = component2;
    return this;
  }

   /**
   * Get component2
   * @return component2
  **/
  @Schema(description = "")
  public ComponentDTO getComponent2() {
    return component2;
  }

  public void setComponent2(ComponentDTO component2) {
    this.component2 = component2;
  }

  public AddressRequestDTO component3(ComponentDTO component3) {
    this.component3 = component3;
    return this;
  }

   /**
   * Get component3
   * @return component3
  **/
  @Schema(description = "")
  public ComponentDTO getComponent3() {
    return component3;
  }

  public void setComponent3(ComponentDTO component3) {
    this.component3 = component3;
  }

  public AddressRequestDTO component4(ComponentDTO component4) {
    this.component4 = component4;
    return this;
  }

   /**
   * Get component4
   * @return component4
  **/
  @Schema(description = "")
  public ComponentDTO getComponent4() {
    return component4;
  }

  public void setComponent4(ComponentDTO component4) {
    this.component4 = component4;
  }

  public AddressRequestDTO component5(ComponentDTO component5) {
    this.component5 = component5;
    return this;
  }

   /**
   * Get component5
   * @return component5
  **/
  @Schema(description = "")
  public ComponentDTO getComponent5() {
    return component5;
  }

  public void setComponent5(ComponentDTO component5) {
    this.component5 = component5;
  }

  public AddressRequestDTO component6(ComponentDTO component6) {
    this.component6 = component6;
    return this;
  }

   /**
   * Get component6
   * @return component6
  **/
  @Schema(description = "")
  public ComponentDTO getComponent6() {
    return component6;
  }

  public void setComponent6(ComponentDTO component6) {
    this.component6 = component6;
  }

  public AddressRequestDTO component7(ComponentDTO component7) {
    this.component7 = component7;
    return this;
  }

   /**
   * Get component7
   * @return component7
  **/
  @Schema(description = "")
  public ComponentDTO getComponent7() {
    return component7;
  }

  public void setComponent7(ComponentDTO component7) {
    this.component7 = component7;
  }

  public AddressRequestDTO component8(ComponentDTO component8) {
    this.component8 = component8;
    return this;
  }

   /**
   * Get component8
   * @return component8
  **/
  @Schema(description = "")
  public ComponentDTO getComponent8() {
    return component8;
  }

  public void setComponent8(ComponentDTO component8) {
    this.component8 = component8;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressRequestDTO addressRequestDTO = (AddressRequestDTO) o;
    return Objects.equals(this.adrId, addressRequestDTO.adrId) &&
        Objects.equals(this.pointX, addressRequestDTO.pointX) &&
        Objects.equals(this.pointY, addressRequestDTO.pointY) &&
        Objects.equals(this.adsAdrId, addressRequestDTO.adsAdrId) &&
        Objects.equals(this.codeAddress, addressRequestDTO.codeAddress) &&
        Objects.equals(this.closeAddress, addressRequestDTO.closeAddress) &&
        Objects.equals(this.fullAddress, addressRequestDTO.fullAddress) &&
        Objects.equals(this.component1, addressRequestDTO.component1) &&
        Objects.equals(this.component2, addressRequestDTO.component2) &&
        Objects.equals(this.component3, addressRequestDTO.component3) &&
        Objects.equals(this.component4, addressRequestDTO.component4) &&
        Objects.equals(this.component5, addressRequestDTO.component5) &&
        Objects.equals(this.component6, addressRequestDTO.component6) &&
        Objects.equals(this.component7, addressRequestDTO.component7) &&
        Objects.equals(this.component8, addressRequestDTO.component8);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adrId, pointX, pointY, adsAdrId, codeAddress, closeAddress, fullAddress, component1, component2, component3, component4, component5, component6, component7, component8);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressRequestDTO {\n");
    
    sb.append("    adrId: ").append(toIndentedString(adrId)).append("\n");
    sb.append("    pointX: ").append(toIndentedString(pointX)).append("\n");
    sb.append("    pointY: ").append(toIndentedString(pointY)).append("\n");
    sb.append("    adsAdrId: ").append(toIndentedString(adsAdrId)).append("\n");
    sb.append("    codeAddress: ").append(toIndentedString(codeAddress)).append("\n");
    sb.append("    closeAddress: ").append(toIndentedString(closeAddress)).append("\n");
    sb.append("    fullAddress: ").append(toIndentedString(fullAddress)).append("\n");
    sb.append("    component1: ").append(toIndentedString(component1)).append("\n");
    sb.append("    component2: ").append(toIndentedString(component2)).append("\n");
    sb.append("    component3: ").append(toIndentedString(component3)).append("\n");
    sb.append("    component4: ").append(toIndentedString(component4)).append("\n");
    sb.append("    component5: ").append(toIndentedString(component5)).append("\n");
    sb.append("    component6: ").append(toIndentedString(component6)).append("\n");
    sb.append("    component7: ").append(toIndentedString(component7)).append("\n");
    sb.append("    component8: ").append(toIndentedString(component8)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
