/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Component
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-06T14:15:06.398175800+03:00[Europe/Helsinki]")
public class Component {
  @SerializedName("id")
  private String id = null;

  @SerializedName("adkv_id")
  private String adkvId = null;

  @SerializedName("nimetus")
  private String nimetus = null;

  @SerializedName("tase")
  private String tase = null;

  @SerializedName("kood")
  private String kood = null;

  @SerializedName("nimetus_liigisonaga")
  private String nimetusLiigisonaga = null;

  @SerializedName("olek")
  private String olek = null;

  @SerializedName("eelmine_id")
  private String eelmineId = null;

  public Component id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "2326354", description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Component adkvId(String adkvId) {
    this.adkvId = adkvId;
    return this;
  }

   /**
   * Get adkvId
   * @return adkvId
  **/
  @Schema(example = "1609278", description = "")
  public String getAdkvId() {
    return adkvId;
  }

  public void setAdkvId(String adkvId) {
    this.adkvId = adkvId;
  }

  public Component nimetus(String nimetus) {
    this.nimetus = nimetus;
    return this;
  }

   /**
   * Get nimetus
   * @return nimetus
  **/
  @Schema(example = "5", description = "")
  public String getNimetus() {
    return nimetus;
  }

  public void setNimetus(String nimetus) {
    this.nimetus = nimetus;
  }

  public Component tase(String tase) {
    this.tase = tase;
    return this;
  }

   /**
   * Get tase
   * @return tase
  **/
  @Schema(example = "7", description = "")
  public String getTase() {
    return tase;
  }

  public void setTase(String tase) {
    this.tase = tase;
  }

  public Component kood(String kood) {
    this.kood = kood;
    return this;
  }

   /**
   * Get kood
   * @return kood
  **/
  @Schema(example = "1DNA", description = "")
  public String getKood() {
    return kood;
  }

  public void setKood(String kood) {
    this.kood = kood;
  }

  public Component nimetusLiigisonaga(String nimetusLiigisonaga) {
    this.nimetusLiigisonaga = nimetusLiigisonaga;
    return this;
  }

   /**
   * Get nimetusLiigisonaga
   * @return nimetusLiigisonaga
  **/
  @Schema(example = "5", description = "")
  public String getNimetusLiigisonaga() {
    return nimetusLiigisonaga;
  }

  public void setNimetusLiigisonaga(String nimetusLiigisonaga) {
    this.nimetusLiigisonaga = nimetusLiigisonaga;
  }

  public Component olek(String olek) {
    this.olek = olek;
    return this;
  }

   /**
   * Get olek
   * @return olek
  **/
  @Schema(example = "K", description = "")
  public String getOlek() {
    return olek;
  }

  public void setOlek(String olek) {
    this.olek = olek;
  }

  public Component eelmineId(String eelmineId) {
    this.eelmineId = eelmineId;
    return this;
  }

   /**
   * Get eelmineId
   * @return eelmineId
  **/
  @Schema(description = "")
  public String getEelmineId() {
    return eelmineId;
  }

  public void setEelmineId(String eelmineId) {
    this.eelmineId = eelmineId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Component component = (Component) o;
    return Objects.equals(this.id, component.id) &&
        Objects.equals(this.adkvId, component.adkvId) &&
        Objects.equals(this.nimetus, component.nimetus) &&
        Objects.equals(this.tase, component.tase) &&
        Objects.equals(this.kood, component.kood) &&
        Objects.equals(this.nimetusLiigisonaga, component.nimetusLiigisonaga) &&
        Objects.equals(this.olek, component.olek) &&
        Objects.equals(this.eelmineId, component.eelmineId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adkvId, nimetus, tase, kood, nimetusLiigisonaga, olek, eelmineId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Component {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adkvId: ").append(toIndentedString(adkvId)).append("\n");
    sb.append("    nimetus: ").append(toIndentedString(nimetus)).append("\n");
    sb.append("    tase: ").append(toIndentedString(tase)).append("\n");
    sb.append("    kood: ").append(toIndentedString(kood)).append("\n");
    sb.append("    nimetusLiigisonaga: ").append(toIndentedString(nimetusLiigisonaga)).append("\n");
    sb.append("    olek: ").append(toIndentedString(olek)).append("\n");
    sb.append("    eelmineId: ").append(toIndentedString(eelmineId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
