/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FeatureProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-06T14:15:06.398175800+03:00[Europe/Helsinki]")
public class FeatureProperties {
  @SerializedName("object_type")
  private String objectType = null;

  @SerializedName("object_code")
  private String objectCode = null;

  @SerializedName("object_address")
  private String objectAddress = null;

  @SerializedName("object_name")
  private String objectName = null;

  public FeatureProperties objectType(String objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Get objectType
   * @return objectType
  **/
  @Schema(example = "EHR_KOOD", description = "")
  public String getObjectType() {
    return objectType;
  }

  public void setObjectType(String objectType) {
    this.objectType = objectType;
  }

  public FeatureProperties objectCode(String objectCode) {
    this.objectCode = objectCode;
    return this;
  }

   /**
   * Get objectCode
   * @return objectCode
  **/
  @Schema(example = "120220828", description = "")
  public String getObjectCode() {
    return objectCode;
  }

  public void setObjectCode(String objectCode) {
    this.objectCode = objectCode;
  }

  public FeatureProperties objectAddress(String objectAddress) {
    this.objectAddress = objectAddress;
    return this;
  }

   /**
   * Get objectAddress
   * @return objectAddress
  **/
  @Schema(example = "Harju maakond, Tallinn, Kesklinna linnaosa, Lõkke tn 4", description = "")
  public String getObjectAddress() {
    return objectAddress;
  }

  public void setObjectAddress(String objectAddress) {
    this.objectAddress = objectAddress;
  }

  public FeatureProperties objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * Get objectName
   * @return objectName
  **/
  @Schema(example = "Administratiivhoone", description = "")
  public String getObjectName() {
    return objectName;
  }

  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureProperties featureProperties = (FeatureProperties) o;
    return Objects.equals(this.objectType, featureProperties.objectType) &&
        Objects.equals(this.objectCode, featureProperties.objectCode) &&
        Objects.equals(this.objectAddress, featureProperties.objectAddress) &&
        Objects.equals(this.objectName, featureProperties.objectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, objectCode, objectAddress, objectName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureProperties {\n");
    
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    objectCode: ").append(toIndentedString(objectCode)).append("\n");
    sb.append("    objectAddress: ").append(toIndentedString(objectAddress)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
