/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AddressRequestDTO;
import io.swagger.client.model.AddressResponseDTO;
import io.swagger.client.model.FeatureList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AadressobjektidApi
 */
@Ignore
public class AadressobjektidApiTest {

    private final AadressobjektidApi api = new AadressobjektidApi();

    /**
     * Aadressi uuendamine või lisamine.
     *
     * Võtab JSON kujul aadressi sisendiks. Address koosneb komponentitest. Vaata lähemalt näidet. Tagastab JSON kujul aadress.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addorupdateaddressPostTest() throws ApiException {
        AddressRequestDTO body = null;
        AddressResponseDTO response = api.addorupdateaddressPost(body);

        // TODO: test validations
    }
    /**
     * Aadressi alusel objektide otsimine. Objektideks on ehitise ruumikujud ehk kui ehitisel on mitu ruumikuju siis tagastatakse ühe EHR koodiga mitu objekti.
     *
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mille aadressid sisaldavad query stringi või ehitise ruumikujud, kui sisend on EHR kood.\\n Koordinaadid XY on kas Lest või WGS84 formaadis.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getgeoobjectsbyaddressGetTest() throws ApiException {
        String address = null;
        String epsg = null;
        String rgo = null;
        FeatureList response = api.getgeoobjectsbyaddressGet(address, epsg, rgo);

        // TODO: test validations
    }
    /**
     * Punkti alusel objektide otsimine
     *
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mis sisaldavad ette antud punkti. Koordinaadid XY. Sisend Lest97 &#x3D;&gt; Väljund Lest97 või sisend WGS84 &#x3D;&gt; Väljund WGS84
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getgeoobjectsbypointGetTest() throws ApiException {
        String lon = null;
        String lat = null;
        FeatureList response = api.getgeoobjectsbypointGet(lon, lat);

        // TODO: test validations
    }
}
