/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AddressComponent;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AadressikomponendidApi
 */
@Ignore
public class AadressikomponendidApiTest {

    private final AadressikomponendidApi api = new AadressikomponendidApi();

    /**
     * Aadressi komponendi alamkomponentide otsimine.
     *
     * Tagastab JSON formaadis aadressi komponendi alamkomponendid. Ülemise taseme komponendid saab ilma komponendi koodita.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addresscomponentchildrenGetTest() throws ApiException {
        BigDecimal id = null;
        AddressComponent response = api.addresscomponentchildrenGet(id);

        // TODO: test validations
    }
}
