/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.AddressComponent;
import java.math.BigDecimal;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AadressikomponendidApi {
    private ApiClient apiClient;

    public AadressikomponendidApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AadressikomponendidApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for addresscomponentchildrenGet
     * @param id Komponendi id, mille alusel leitakse alamad. Juhul, kui id puudub siis tagastatakse kõik ülemise taseme komponendid. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call addresscomponentchildrenGetCall(BigDecimal id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/addresscomponentchildren";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (id != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("id", id));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call addresscomponentchildrenGetValidateBeforeCall(BigDecimal id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = addresscomponentchildrenGetCall(id, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Aadressi komponendi alamkomponentide otsimine.
     * Tagastab JSON formaadis aadressi komponendi alamkomponendid. Ülemise taseme komponendid saab ilma komponendi koodita.
     * @param id Komponendi id, mille alusel leitakse alamad. Juhul, kui id puudub siis tagastatakse kõik ülemise taseme komponendid. (optional)
     * @return AddressComponent
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AddressComponent addresscomponentchildrenGet(BigDecimal id) throws ApiException {
        ApiResponse<AddressComponent> resp = addresscomponentchildrenGetWithHttpInfo(id);
        return resp.getData();
    }

    /**
     * Aadressi komponendi alamkomponentide otsimine.
     * Tagastab JSON formaadis aadressi komponendi alamkomponendid. Ülemise taseme komponendid saab ilma komponendi koodita.
     * @param id Komponendi id, mille alusel leitakse alamad. Juhul, kui id puudub siis tagastatakse kõik ülemise taseme komponendid. (optional)
     * @return ApiResponse&lt;AddressComponent&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AddressComponent> addresscomponentchildrenGetWithHttpInfo(BigDecimal id) throws ApiException {
        com.squareup.okhttp.Call call = addresscomponentchildrenGetValidateBeforeCall(id, null, null);
        Type localVarReturnType = new TypeToken<AddressComponent>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Aadressi komponendi alamkomponentide otsimine. (asynchronously)
     * Tagastab JSON formaadis aadressi komponendi alamkomponendid. Ülemise taseme komponendid saab ilma komponendi koodita.
     * @param id Komponendi id, mille alusel leitakse alamad. Juhul, kui id puudub siis tagastatakse kõik ülemise taseme komponendid. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call addresscomponentchildrenGetAsync(BigDecimal id, final ApiCallback<AddressComponent> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = addresscomponentchildrenGetValidateBeforeCall(id, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AddressComponent>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
