/*
 * Geoinfo
 * Ehitisregistri geoteenused.   Kood asub: [https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices](https://git.mkm.ee/ehr/ehr-k8s-pipeline/ehr-geoservices)
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ulo.puskar@mkm.ee
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.AddressRequestDTO;
import io.swagger.client.model.AddressResponseDTO;
import io.swagger.client.model.FeatureList;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AadressobjektidApi {
    private ApiClient apiClient;

    public AadressobjektidApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AadressobjektidApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for addorupdateaddressPost
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call addorupdateaddressPostCall(AddressRequestDTO body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/addorupdateaddress";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call addorupdateaddressPostValidateBeforeCall(AddressRequestDTO body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = addorupdateaddressPostCall(body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Aadressi uuendamine või lisamine.
     * Võtab JSON kujul aadressi sisendiks. Address koosneb komponentitest. Vaata lähemalt näidet. Tagastab JSON kujul aadress.
     * @param body  (optional)
     * @return AddressResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AddressResponseDTO addorupdateaddressPost(AddressRequestDTO body) throws ApiException {
        ApiResponse<AddressResponseDTO> resp = addorupdateaddressPostWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * Aadressi uuendamine või lisamine.
     * Võtab JSON kujul aadressi sisendiks. Address koosneb komponentitest. Vaata lähemalt näidet. Tagastab JSON kujul aadress.
     * @param body  (optional)
     * @return ApiResponse&lt;AddressResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AddressResponseDTO> addorupdateaddressPostWithHttpInfo(AddressRequestDTO body) throws ApiException {
        com.squareup.okhttp.Call call = addorupdateaddressPostValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<AddressResponseDTO>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Aadressi uuendamine või lisamine. (asynchronously)
     * Võtab JSON kujul aadressi sisendiks. Address koosneb komponentitest. Vaata lähemalt näidet. Tagastab JSON kujul aadress.
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call addorupdateaddressPostAsync(AddressRequestDTO body, final ApiCallback<AddressResponseDTO> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = addorupdateaddressPostValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AddressResponseDTO>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getgeoobjectsbyaddressGet
     * @param address Aadressi string mille alusel otsitakse või EHR kood (11 arvsümbolit) (required)
     * @param epsg Kui &#x3D; \&quot;wgs84\&quot; siis tagastab koordinaadid WGS84 formaadis (optional)
     * @param rgo Kui true siis tagastab objektid, millel on ruumikuju olemas, kui false siis tagastab ka ruumikujuta objektid. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getgeoobjectsbyaddressGetCall(String address, String epsg, String rgo, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/getgeoobjectsbyaddress";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (address != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("address", address));
        if (epsg != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("epsg", epsg));
        if (rgo != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("rgo", rgo));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getgeoobjectsbyaddressGetValidateBeforeCall(String address, String epsg, String rgo, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'address' is set
        if (address == null) {
            throw new ApiException("Missing the required parameter 'address' when calling getgeoobjectsbyaddressGet(Async)");
        }
        
        com.squareup.okhttp.Call call = getgeoobjectsbyaddressGetCall(address, epsg, rgo, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Aadressi alusel objektide otsimine. Objektideks on ehitise ruumikujud ehk kui ehitisel on mitu ruumikuju siis tagastatakse ühe EHR koodiga mitu objekti.
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mille aadressid sisaldavad query stringi või ehitise ruumikujud, kui sisend on EHR kood.\\n Koordinaadid XY on kas Lest või WGS84 formaadis.
     * @param address Aadressi string mille alusel otsitakse või EHR kood (11 arvsümbolit) (required)
     * @param epsg Kui &#x3D; \&quot;wgs84\&quot; siis tagastab koordinaadid WGS84 formaadis (optional)
     * @param rgo Kui true siis tagastab objektid, millel on ruumikuju olemas, kui false siis tagastab ka ruumikujuta objektid. (optional)
     * @return FeatureList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public FeatureList getgeoobjectsbyaddressGet(String address, String epsg, String rgo) throws ApiException {
        ApiResponse<FeatureList> resp = getgeoobjectsbyaddressGetWithHttpInfo(address, epsg, rgo);
        return resp.getData();
    }

    /**
     * Aadressi alusel objektide otsimine. Objektideks on ehitise ruumikujud ehk kui ehitisel on mitu ruumikuju siis tagastatakse ühe EHR koodiga mitu objekti.
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mille aadressid sisaldavad query stringi või ehitise ruumikujud, kui sisend on EHR kood.\\n Koordinaadid XY on kas Lest või WGS84 formaadis.
     * @param address Aadressi string mille alusel otsitakse või EHR kood (11 arvsümbolit) (required)
     * @param epsg Kui &#x3D; \&quot;wgs84\&quot; siis tagastab koordinaadid WGS84 formaadis (optional)
     * @param rgo Kui true siis tagastab objektid, millel on ruumikuju olemas, kui false siis tagastab ka ruumikujuta objektid. (optional)
     * @return ApiResponse&lt;FeatureList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<FeatureList> getgeoobjectsbyaddressGetWithHttpInfo(String address, String epsg, String rgo) throws ApiException {
        com.squareup.okhttp.Call call = getgeoobjectsbyaddressGetValidateBeforeCall(address, epsg, rgo, null, null);
        Type localVarReturnType = new TypeToken<FeatureList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Aadressi alusel objektide otsimine. Objektideks on ehitise ruumikujud ehk kui ehitisel on mitu ruumikuju siis tagastatakse ühe EHR koodiga mitu objekti. (asynchronously)
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mille aadressid sisaldavad query stringi või ehitise ruumikujud, kui sisend on EHR kood.\\n Koordinaadid XY on kas Lest või WGS84 formaadis.
     * @param address Aadressi string mille alusel otsitakse või EHR kood (11 arvsümbolit) (required)
     * @param epsg Kui &#x3D; \&quot;wgs84\&quot; siis tagastab koordinaadid WGS84 formaadis (optional)
     * @param rgo Kui true siis tagastab objektid, millel on ruumikuju olemas, kui false siis tagastab ka ruumikujuta objektid. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getgeoobjectsbyaddressGetAsync(String address, String epsg, String rgo, final ApiCallback<FeatureList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getgeoobjectsbyaddressGetValidateBeforeCall(address, epsg, rgo, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<FeatureList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getgeoobjectsbypointGet
     * @param lon Longitude ehk X kas WGS või LEST (required)
     * @param lat Latitude ehk Y kas WGS või LEST (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getgeoobjectsbypointGetCall(String lon, String lat, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/getgeoobjectsbypoint";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (lon != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("lon", lon));
        if (lat != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("lat", lat));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getgeoobjectsbypointGetValidateBeforeCall(String lon, String lat, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'lon' is set
        if (lon == null) {
            throw new ApiException("Missing the required parameter 'lon' when calling getgeoobjectsbypointGet(Async)");
        }
        // verify the required parameter 'lat' is set
        if (lat == null) {
            throw new ApiException("Missing the required parameter 'lat' when calling getgeoobjectsbypointGet(Async)");
        }
        
        com.squareup.okhttp.Call call = getgeoobjectsbypointGetCall(lon, lat, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Punkti alusel objektide otsimine
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mis sisaldavad ette antud punkti. Koordinaadid XY. Sisend Lest97 &#x3D;&gt; Väljund Lest97 või sisend WGS84 &#x3D;&gt; Väljund WGS84
     * @param lon Longitude ehk X kas WGS või LEST (required)
     * @param lat Latitude ehk Y kas WGS või LEST (required)
     * @return FeatureList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public FeatureList getgeoobjectsbypointGet(String lon, String lat) throws ApiException {
        ApiResponse<FeatureList> resp = getgeoobjectsbypointGetWithHttpInfo(lon, lat);
        return resp.getData();
    }

    /**
     * Punkti alusel objektide otsimine
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mis sisaldavad ette antud punkti. Koordinaadid XY. Sisend Lest97 &#x3D;&gt; Väljund Lest97 või sisend WGS84 &#x3D;&gt; Väljund WGS84
     * @param lon Longitude ehk X kas WGS või LEST (required)
     * @param lat Latitude ehk Y kas WGS või LEST (required)
     * @return ApiResponse&lt;FeatureList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<FeatureList> getgeoobjectsbypointGetWithHttpInfo(String lon, String lat) throws ApiException {
        com.squareup.okhttp.Call call = getgeoobjectsbypointGetValidateBeforeCall(lon, lat, null, null);
        Type localVarReturnType = new TypeToken<FeatureList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Punkti alusel objektide otsimine (asynchronously)
     * Tagastab GeoJson formaadis kuni 100 aadressiobjekti, mis sisaldavad ette antud punkti. Koordinaadid XY. Sisend Lest97 &#x3D;&gt; Väljund Lest97 või sisend WGS84 &#x3D;&gt; Väljund WGS84
     * @param lon Longitude ehk X kas WGS või LEST (required)
     * @param lat Latitude ehk Y kas WGS või LEST (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getgeoobjectsbypointGetAsync(String lon, String lat, final ApiCallback<FeatureList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getgeoobjectsbypointGetValidateBeforeCall(lon, lat, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<FeatureList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
